# MERT optimized configuration
# decoder /workspace/tools/mosesdecoder/bin/moses
# BLEU 0.785445 on dev /workspace/exp/clean-data/dev.ph
# We were before running iteration 4
# finished Tue Jun 16 18:15:57 UTC 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/workspace/exp/ph-my/model/model/phrase-table.gz input-factor=0 output-factor=0
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/workspace/exp/ph-my/model/model/reordering-table.wbe-msd-bidirectional-fe.gz
Distortion
KENLM name=LM0 factor=0 path=/workspace/exp/ph-my/lm/train.my.blm order=5

# dense weights for feature functions

[threads]
4
[weight]

LexicalReordering0= 0.000976906 0.00305103 0.000365856 -0.000688238 0.000350298 0.000915882
Distortion0= 0.000198567
LM0= 0.000485535
WordPenalty0= 0.000649126
PhrasePenalty0= -0.99161
TranslationModel0= 9.21604e-05 0.000530087 2.18402e-05 6.46264e-05
UnknownWordPenalty0= 1
