# MERT optimized configuration
# decoder /workspace/tools/mosesdecoder/bin/moses
# BLEU 0.781919 on dev /workspace/exp/clean-data/dev.ph
# We were before running iteration 2
# finished Tue Jun 16 18:13:30 UTC 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/workspace/exp/ph-my/model/model/phrase-table.gz input-factor=0 output-factor=0
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/workspace/exp/ph-my/model/model/reordering-table.wbe-msd-bidirectional-fe.gz
Distortion
KENLM name=LM0 factor=0 path=/workspace/exp/ph-my/lm/train.my.blm order=5

# dense weights for feature functions

[threads]
4
[weight]

LexicalReordering0= 0.0256662 0.420248 0.0460164 0.032253 0.0515975 0.0506581
Distortion0= 0.0417311
LM0= 0.0579198
WordPenalty0= 0.0272902
PhrasePenalty0= -0.15854
TranslationModel0= 0.00637045 0.0592918 -0.00246074 0.0199569
UnknownWordPenalty0= 1
