# MERT optimized configuration
# decoder /workspace/tools/mosesdecoder/bin/moses
# BLEU 0.783121 on dev /workspace/exp/clean-data/dev.ph
# We were before running iteration 3
# finished Tue Jun 16 18:14:16 UTC 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/workspace/exp/ph-my/model/model/phrase-table.gz input-factor=0 output-factor=0
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/workspace/exp/ph-my/model/model/reordering-table.wbe-msd-bidirectional-fe.gz
Distortion
KENLM name=LM0 factor=0 path=/workspace/exp/ph-my/lm/train.my.blm order=5

# dense weights for feature functions

[threads]
4
[weight]

LexicalReordering0= 0.0886253 0.0898732 0.322976 0.0406467 0.0162274 0.0166234
Distortion0= 0.0887
LM0= 0.091988
WordPenalty0= 0.0822327
PhrasePenalty0= -0.0248922
TranslationModel0= 0.0688632 0.042964 0.0209419 -0.00444583
UnknownWordPenalty0= 1
