# MERT optimized configuration
# decoder /workspace/tools/mosesdecoder/bin/moses
# BLEU 0.695924 on dev /workspace/exp/clean-data/dev.my
# We were before running iteration 2
# finished Tue Jun 16 18:08:27 UTC 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/workspace/exp/my-ph/model/model/phrase-table.gz input-factor=0 output-factor=0
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/workspace/exp/my-ph/model/model/reordering-table.wbe-msd-bidirectional-fe.gz
Distortion
KENLM name=LM0 factor=0 path=/workspace/exp/my-ph/lm/train.ph.blm order=5

# dense weights for feature functions

[threads]
4
[weight]

LexicalReordering0= 0.0302375 0.00825324 0.0324733 0.0977332 0.0108432 0.168259
Distortion0= 0.157857
LM0= 0.0754295
WordPenalty0= 0.110359
PhrasePenalty0= 0.0208964
TranslationModel0= 0.168968 -0.0136181 -0.0354876 0.0695845
UnknownWordPenalty0= 1
