# MERT optimized configuration
# decoder /workspace/tools/mosesdecoder/bin/moses
# BLEU 0.694511 on dev /workspace/exp/clean-data/dev.my
# We were before running iteration 3
# finished Tue Jun 16 18:09:11 UTC 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/workspace/exp/my-ph/model/model/phrase-table.gz input-factor=0 output-factor=0
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/workspace/exp/my-ph/model/model/reordering-table.wbe-msd-bidirectional-fe.gz
Distortion
KENLM name=LM0 factor=0 path=/workspace/exp/my-ph/lm/train.ph.blm order=5

# dense weights for feature functions

[threads]
4
[weight]

LexicalReordering0= 0.0300401 0.00819935 0.0322613 0.097095 0.0107724 0.16716
Distortion0= 0.156826
LM0= 0.074937
WordPenalty0= 0.125571
PhrasePenalty0= 0.02076
TranslationModel0= 0.167865 -0.0135292 -0.0215773 0.0734067
UnknownWordPenalty0= 1
